repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-added-large-files
        args: ["--maxkb=100"]  # Optional: Ensure files aren't too large
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: name-tests-test
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-xml

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: ^dist/|^docs/|^tests/|^migrations/
        args: [--line-length=79]


-   repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8
        args: ["--max-line-length=91"]  # Black's default line length
        exclude: migrations/
