
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=${CELERY_BROKER_URL}
      - CELERY_BACKEND=${CELERY_BROKER_URL}
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - pay_network

  redis:
    image: redis:alpine
    container_name: scheduler_redis

  celery:
    build: .
    command: celery -A CORE.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command:
      [
        'celery',
        '--app=CORE',
        'beat',
        '--scheduler=django_celery_beat.schedulers:DatabaseScheduler',
        '--loglevel=INFO',
      ]
    volumes:
      - ./:/app
    depends_on:
      - web
      - redis

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
  redis_data:

networks:
  pay_network:
    driver: bridge
