# Generated by Django 4.2.13 on 2024-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency_symbol',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
