# Generated by Django 4.2.13 on 2024-06-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "payment",
            "0002_remove_wallet_currency_symbol_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="NGN", max_length=3),
        ),
        migrations.CreateModel(
            name="ScheduledPayment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=payment.models.generate_id,
                        editable=False,
                        max_length=70,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("fullfilled", "Fullfilled"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("schedule_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
